name: flutter_course
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  geolocator: ^8.1.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.3
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  loading_overlay: ^0.3.0
  flutter_slidable: ^1.2.0
  marquee: ^2.2.1
  flutter_native_splash: ^2.1.1
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#533758"
  image: assets/PocketMechanicLogo5.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: PatuaOne
      fonts:
        - asset: fonts/PatuaOne-Regular.ttf
