final vehicleBrands = [
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'BMW',
  'Baic',
  'Bestune',
  'Brilliance',
  'Byd',
  'Canghe',
  'Changan',
  'Chery',
  'Chevrolet',
  'Citroën',
  'DFM',
  'DFSK',
  'Ds',
  'Dodge',
  'Fiat',
  'Ford',
  'Geely',
  'Haval',
  'Honda',
  'Hyundai',
  'Jac',
  'Jaguar',
  'Jeep',
  'Jetour',
  'Kia',
  'Lada',
  'Land Rover',
  'Lexus',
  'MG',
  'Maserati',
  'Mazda',
  'Mercedes',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Proton',
  'Renault',
  'Seat',
  'Skoda',
  'Soueast',
  'Ssang Yong',
  'Subaru',
  'Suzuki',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Zotye',
];

final bodyTypes = ['Sedan', 'SUV', 'Hatchback', 'Coupe', 'MiniVan'];

final vehicleBrandBodyType = {
  'DFM': ['Sedan'],
  'Hyundai': ['Sedan', 'SUV', 'Hatchback'],
  'Chery': ['Sedan', 'SUV'],
  'Kia': ['Sedan', '4X4', 'SUV'],
  'Chevrolet': ['Sedan', 'SUV'],
  'Fiat': ['Sedan', 'SUV', 'Hatchback', 'Coupe', 'MiniVan'],
  'Nissan': ['Sedan', '4X4', 'SUV'],
  'Renault': [
    'Sedan',
    'SUV',
    'Hatchback',
  ],
  'Volkswagen': ['Sedan', 'SUV'],
  'Mercedes': ['Sedan', '4X4', 'SUV', 'Hatchback', 'Coupe'],
  'MG': ['Sedan', 'SUV'],
  'BMW': ['Sedan', '4X4', 'SUV', 'Hatchback', 'Coupe'],
  'Mitsubishi': ['4X4', 'SUV'],
  'Toyota': ['Sedan', '4X4', 'SUV', 'Hatchback', 'MiniVan'],
  'Land Rover': ['4X4'],
  'Mazda': ['Sedan', 'SUV'],
  'Subaru': ['Sedan', 'SUV'],
  'Lada': ['Sedan', 'MiniVan'],
  'Geely': ['SUV'],
  'Jac': ['Sedan', 'SUV'],
  'Opel': ['Sedan', 'SUV', 'Hatchback'],
  'Honda': ['Sedan', 'SUV', 'Hatchback'],
  'Mini': ['SUV', 'Hatchback', 'Coupe', ''],
  'Audi': ['Sedan', '4X4', 'SUV', 'MiniVan'],
  'DFSK': ['SUV', 'MiniVan'],
  'Skoda': ['Sedan', 'SUV', 'Hatchback'],
  'Brilliance': [
    'SUV',
  ],
  'Jaguar': ['Sedan', '4X4', 'SUV', 'Coupe'],
  'Canghe': ['SUV', 'MiniVan'],
  'Proton': ['Sedan', 'Hatchback'],
  'Porsche': ['4X4', 'Hatchback', 'Coupe'],
  'Byd': ['Sedan'],
  'Jeep': ['4X4', 'SUV'],
  'Ford': ['Sedan', 'SUV', 'Hatchback'],
  'Changan': ['Sedan', 'SUV', ''],
  'Ds': ['SUV'],
  'Seat': ['SUV', 'Hatchback'],
  'Zotye': ['Sedan', 'SUV', 'Hatchback'],
  'Citroën': ['Sedan', 'SUV', 'Hatchback', 'MiniVan'],
  'Suzuki': ['Sedan', 'SUZ', 'Hatchback', 'MiniVan'],
  'Jetour': ['SUV'],
  'Alfa Romeo': ['Sedan', 'SUV', 'Hatchback', 'Coupe'],
  'Peugeot': ['Sedan', 'SUV', ''],
  'Volvo': ['4X4', 'SUV'],
  'Bestune': ['Sedan', 'SUV'],
  'Ssang Yong': ['SUV'],
  'Lexus': ['Sedan', '4X4', 'SUV'],
  'Aston Martin': ['Coupe'],
  'Baic': ['SUV'],
  'Haval': ['SUV'],
  'Soueast': [
    'Sedan',
    'SUV',
  ],
  'Maserati': [
    'Sedan',
    '4X4',
  ]
};

final vehicleColors = [
  'White',
  'Black',
  'Grey',
  'Silver',
  'Red',
  'Blue',
  'Brown',
  'Green',
  'Beige',
  'Orange',
  'Gold',
  'Yellow',
  'Purple'
];
final modelYear = [
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
  '2016',
  '2015',
  '2014',
  '2013',
  '2012',
  '2011',
  '2010',
  '2009',
  '2008',
  '2007',
  '2006',
  '2005',
  '2004',
  '2003',
  '2002',
  '2001',
  '2000'
];
final transimissionTypes = ['Manual', 'Automatic'];
